docs/DeveloperGuide.md

Update NFR section of DG

---

docs/UserGuide.md

Update Command Summary in UG

---

docs/DeveloperGuide.md

- changes the System for use cases to RTPM
- adds UC4 to UC6 using the same format as the sample UC

Update UC4 to UC6 of DG

---

docs/AboutUs.md
docs/team/j-hta-n.md

Renames the .png and .md files for ppp

#8. Rename files for ppp

---

src/main/java/seedu/address/logic/commands/ListSellersCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/model/Model.java

When 'list-s' is entered, the addressbook list is filtered to show only sellers.

[Closes #4] Add view sellers command

---

src/main/java/seedu/address/model/person/buyer/BuyHouseInfo.java
src/main/java/seedu/address/model/person/buyer/Buyer.java
src/main/java/seedu/address/model/person/seller/SellHouseInfo.java
src/main/java/seedu/address/model/person/seller/Seller.java
src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
src/main/java/seedu/address/storage/JsonAdaptedSeller.java

[#7] Add Json adapted buyers and sellers

---

src/main/java/seedu/address/ui/BuyerCard.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/SellerCard.java

[#50] Add cards and abstractify PersonCard

---

src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/StorageManager.java
src/test/java/seedu/address/logic/parser/AddBuyerCommandParserTest.java

[#62] Add BuyerCommandParser tests

---

src/test/java/seedu/address/logic/commands/DeleteBuyerCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteSellerCommandTest.java

Add DeleteBuyerCommandTest and DeleteSellerCommandTest.

Add Delete Command Tests

---

src/main/resources/view/BuyerListCard.fxml
src/main/resources/view/DisplayableListPanel.fxml
src/main/resources/view/MainWindow.fxml
src/main/resources/view/SellerListCard.fxml

Creates new fxml files (BuyerListCard.fxml, SellerListCard.fxml, DisplayableListPanel.fxml) and modifies existing fxml files to include new components (MainWindow.fxml).
In essence, any @FXML tag in the JavaFX handlers must match the components in the corresponding .fxml files, else a NullPointerException is thrown when either the .fxml file or the fxml components are missing.

[#61] Fix ui errors

---

src/test/java/seedu/address/logic/commands/DeleteBuyerCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteSellerCommandTest.java

[#62] Reorder import statements

---

docs/UserGuide.md
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
src/main/java/seedu/address/logic/commands/AddSellerCommand.java
src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/test/java/seedu/address/logic/LogicManagerTest.java

Some changes to the user guide as well; actual output messages for add and delete commands for both buyers and sellers should be aligned with the user guide now

Make output messages match those given in the user guide

---

src/test/java/seedu/address/logic/commands/ListBuyersCommandTest.java

Add ListBuyersCommandTest

---

src/test/java/seedu/address/model/person/BuyerTest.java
src/test/java/seedu/address/model/person/SellerTest.java

Add BuyerTest and SellerTest
Replace PersonTest

Add BuyerTest and SellerTest

---

src/main/java/seedu/address/model/displayable/Priority.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/SetBuyerPriorityCommandParserTest.java
src/test/java/seedu/address/logic/parser/SetSellerPriorityCommandParserTest.java
src/test/java/seedu/address/model/displayable/PriorityTest.java
src/test/java/seedu/address/testutil/TypicalPriorities.java

Namely test cases for priority and priority command parser

[#107] Add more test cases for Priority

---

src/main/java/seedu/address/logic/commands/SortBuyerCommand.java
src/main/java/seedu/address/logic/commands/SortSellerCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/SortBuyerCommandParser.java
src/main/java/seedu/address/logic/parser/SortSellerCommandParser.java
src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java

Fix Sort commands to use CommandWarnings

---

docs/DeveloperGuide.md
docs/diagrams/isAppropriateNameSequenceDiagram.puml
docs/diagrams/temp.puml
docs/index.md

Adds a sequence diagram and explains the implementation of CommandWarnings to solve the problem of overly stringent field verification. Minor fixes to Index.md.

Update DG for implementation of CommandWarnings, minor fixes

---

src/main/java/seedu/address/commons/util/StringUtil.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
src/main/java/seedu/address/logic/commands/AddSellerCommand.java
src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
src/main/java/seedu/address/logic/commands/EditSellerCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/displayable/Displayable.java
src/main/java/seedu/address/model/displayable/Name.java
src/main/java/seedu/address/model/displayable/Person.java
src/main/java/seedu/address/model/displayable/UniqueDisplayableList.java
src/main/java/seedu/address/model/displayable/buyer/Buyer.java
src/main/java/seedu/address/model/displayable/house/House.java
src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java

This pull request implements a fuzzy matching feature to names for displayables. Names can be checked for similarity, which is used in edit and add commands to warn the user if the system detects such similarities.

[#151] Implement fuzzy name matching and warning

---

src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java

Allow case-insensitive prefixes

---

src/main/java/seedu/address/logic/commands/SortBuyerCommand.java
src/main/java/seedu/address/logic/commands/SortSellerCommand.java
src/main/java/seedu/address/logic/parser/SortBuyerCommandParser.java
src/main/java/seedu/address/logic/parser/SortSellerCommandParser.java
src/main/java/seedu/address/model/ModelManager.java

Add default sort and make sort non-case sensitive

[Closes #146, #148] Update sort feature

---

docs/UserGuide.md

Resolves issues caused by the PR #165, where certain commands were not included properly.
Added a section explaining the warning system.

Fix UG errors and omissions

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
src/main/java/seedu/address/logic/commands/AddSellerCommand.java
src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
src/main/java/seedu/address/model/displayable/Priority.java

Mostly changes to the UG's SetPriority commands.
Also modifies AddBuyer and AddSeller commands to support addition of priority levels, which is reflected in UG.

Update UG for set priority commands

---

src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/java/seedu/address/model/util/SampleDataUtilTest.java

Previously our logging and UG informed users that there was supposed to be a sample addressbook loaded when this was not true. This pull request should resolve that.

Add default addressbook

---

docs/UserGuide.md

Edit the "Precise outputs when the command fails due to missing parameters"

Edit User Guide for accuracy

---

docs/AboutUs.md
docs/DeveloperGuide.md
docs/diagrams/EditBuyerSequenceDiagram.puml
docs/team/iantsaii.md

Update PPP to make it look cleaner
Update 'edit' portion of DG

Update PPP and DG

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/team/ruiyangzh.md

Improved UG q&a, added more DG planned enhancements, PPP reformatted for nicer printing.

Minor touch-ups to documentation

---

src/main/java/seedu/address/model/displayable/Priority.java
src/test/java/seedu/address/model/displayable/PriorityTest.java

Also fixes a minor validation regex bug which doesn't affect the app's behaviour, but which affects a particular internal test case

Add more tests for priority

---

docs/UserGuide.md

Improve appendices, FAQ and intro sections.

Partial improvement of UG

---

docs/UserGuide.md

Edit the "add" and "edit" commands descriptions.

Edit content of UG

---

docs/UserGuide.md

Split command features into two separate sections.

Reformat features section
